<div class="news_middle fl claerfix">

			        			<div class="news_top news_bottom">
			        				<h3>[field:fulltitle/]</h3>
			        				<span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
			        				<p>[field:description function="cn_substr(@me,500)"/]...</p>
			        			</div>
			        			
			        			<!-- <div class="news_bottom">
			        				<h3>四种方式  你看懂了么？</h3>
			        				<span>2016-10-28</span>
			        				<p>近年，随着国内很多理财市场的逐渐下调，很多投资者已开始向外币理财市场靠拢。近年，随着国内很多理财市场的逐渐下调</p>
			        			</div> -->
			        		</div>