<div class="main"><img src="{dede:global.cfg_templets_skin/}/images/AD0I4oLBBRAEGAAgpomXwAUohYSY8AYwJzg0.png">
    			<span><img src="{dede:global.cfg_templets_skin/}/images/AD0I4oLBBRAEGAAgpomXwAUohYSY8AYwJzg0.png"></span>
    			<a href="[field:arcurl/] "><h4>[field:fulltitle/] </h4></a><div style="float:right;border: 1px solid red;margin-top: 40px;color: #666666;"><b>[field:pubdate function="MyDate('m/d/Y',@me)"/]</b></div>
    			<p>[field:description function="cn_substr(@me,120)"/]...</p>
    		</div>