<div class="main">
    			<span><a style="width:100px;-border: 1px solid red;margin-top: -30px;font-weight:bold ;margin-left: -50px">[field:pubdate function="MyDate('m/d/Y',@me)"/]</a></span>
    			<a href="[field:arcurl/] "><h4>[field:fulltitle/] <div style="float:right;border: 1px solid red;margin-top: 50px">aa</div></h4></a><div style="float:right;border: 1px solid red;margin-top: 50px">aa</div>
    			<p>[field:description function="cn_substr(@me,120)"/]...</p>
    		</div>