<!-- <p href="[field:typeurl/]">[field:title/]</p> -->

			        			<img class="Imga" src="[field:picname/]">
			        			<div class="neirong fr claerfix">

			        				<h4>[field:title/]</h4>
				        			<p>
				        				{dede:field.content/}
				        			</p>
			        			</div>
			        			
			        			<div class="more">
			        				<a href="[field:arcurl/]">查看详情</a>
			        			</div>