<div class="public_box">
		   				<div class="public_left fl claerfix">
			   				<img src="[field:picname/]">
			   			</div>
			   			<div class="public_right fr claerfix">
			   				<h3>[field:title/]</h3>
			   				<p>
			   					[field:description function="cn_substr(@me,00)"/]...
			   				</p>
			   				<section>公益组织：深圳壹基金公益基金会</section>
			   				
			   				<div class="checkmore">
			   					<a href="[field:arcurl/]">查看详情</a>
			   				</div>
			   			</div>
		   			</div>