<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",217,249);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("list","\r\n		   			<div class=\"public_box\">\r\n		   				<div class=\"public_left fl claerfix\">\r\n			   				<img src=\"[field:picname/]\">\r\n			   			</div>\r\n			   			<div class=\"public_right fr claerfix\">\r\n			   				<h3>[field:title/]</h3>\r\n			   				<p>\r\n			   					[field:description function=\"cn_substr(@me,500)\"/]...\r\n			   				</p>\r\n			   				<section>公益组织：深圳壹基金公益基金会</section>\r\n			   				\r\n			   				<div class=\"checkmore\">\r\n			   					<a href=\"[field:arcurl/]\">查看详情</a>\r\n			   				</div>\r\n			   			</div>\r\n		   			</div>\r\n		   		",370,965);
$z[2][4]['pagesize']="5";
$z[3]=Array("pagelist","",1036,1113);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="2";
$z[4]=Array("include","",1199,1236);
$z[4][4]['filename']="footer.htm";

?>