<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",76,108);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("list","\r\n    		<div class=\"main\">\r\n    			<span><img style=\"margin-top: 15px;margin-left: 20px\" src=\"/templets/xinwen/images/AD0I4oLBBRAEGAAgpomXwAUohYSY8AYwJzg0.png\"></span>\r\n    			<a href=\"[field:arcurl/] \"><h4>[field:fulltitle/] </h4></a><div style=\"float:right;margin-top: 40px;color: #666666;\"><b>[field:pubdate function=\"MyDate('m/d/Y',@me)\"/]</b></div><br>\r\n    			<p>[field:description function=\"cn_substr(@me,120)\"/]...</p>\r\n    		</div>\r\n    		",246,731);
$z[2][4]['pagesize']="4";
$z[3]=Array("pagelist","",832,909);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="3";
$z[4]=Array("include","",933,970);
$z[4][4]['filename']="footer.htm";

?>