<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[21]=array(12,1,1,'5biC5Zy65YiG5p6Q');
$cfg_Cs[20]=array(12,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[19]=array(0,1,1,'5oub6IGY');
$cfg_Cs[18]=array(0,1,1,'5ZCI5L2c5py65p6E');
$cfg_Cs[17]=array(0,1,1,'56S+5Lya5YWs55uK');
$cfg_Cs[16]=array(15,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[15]=array(0,1,1,'6KGM5Lia6LWE6K6v');
$cfg_Cs[14]=array(13,1,1,'5YWs5Y+45p625p6E');
$cfg_Cs[12]=array(0,1,1,'6aaW6aG1');
$cfg_Cs[13]=array(0,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[22]=array(12,1,1,'55CG6LSi5paw6LWE6K6v');
?>